language: elixir
sudo:     false

jobs:
  include:
    - stage:         test
      elixir:        1.2.0
      otp_release:   18.0
      env:           MIX_ENV=test
      after_success: mix coveralls.travis
    - stage:       verify
      elixir:      1.2.0
      otp_release: 18.0
      env:         MIX_ENV=prod
      script: |-
        cd "${TRAVIS_BUILD_DIR}/verify"
        mix compile
        mix ref_inspector.verify
