name: Verification

on:
  push:
  pull_request:
  schedule:
    - cron: '15 16 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      id: setup
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.11.3'
        otp-version: '23.0'

    - name: mix-cache
      uses: actions/cache@v1
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ steps.setup.outputs.otp-version }}-${{ steps.setup.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: mix-deps
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: verify
      run: mix ref_inspector.verify
      working-directory: ./verify
