name: Verification

on:
  pull_request:
  push:
    branches:
      - master
      - test
    tags:
      - '*'
  schedule:
    - cron: '15 16 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: setup
        id: setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '27.2'

      - name: mix-cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-${{ steps.setup.outputs.otp-version }}-${{ steps.setup.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: mix-deps
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: verify
        run: mix ref_inspector.verify
        working-directory: ./verify
